// GENERATED by scripts/gen_smufl.py from the Bravura metadata. Do not edit.
//
// Bravura is (c) Steinberg Media Technologies GmbH, under the SIL Open Font
// License 1.1. Only the glyphs this renderer draws are carried over here.

/// One glyph of the music font: what to draw it with, and how much room it
/// takes. Every measurement is in staff spaces, which is how the metadata
/// states them and how the layout thinks.
class Glyph {
  const Glyph(this.name, this.char, this.advance, this.left, this.right,
      this.top, this.bottom, {this.stemUpSE, this.stemDownNW});

  /// The SMuFL name, which is what the metadata calls it.
  final String name;

  /// The character to set in Bravura to get it.
  final String char;

  /// How far the pen moves after drawing it.
  final double advance;

  /// The box it actually covers, measured from the origin. Up is positive
  /// here, the way the font states it; the renderer flips it.
  final double left;
  final double right;
  final double top;
  final double bottom;

  /// Where a stem meets it, when it is a notehead. Up-stems attach on the
  /// right, down-stems on the left, and neither sits exactly at the corner —
  /// which is why these are read rather than guessed.
  final List<double>? stemUpSE;
  final List<double>? stemDownNW;

  double get width => right - left;
  double get height => top - bottom;

  @override
  String toString() => 'Glyph($name)';
}

/// How thick the lines of the engraving are, as the font says they should
/// be. Everything drawn as a shape rather than as a glyph — staff lines,
/// stems, beams, barlines, ties — is drawn to these.
class EngravingDefaults {
  static const double arrowShaftThickness = 0.16;
  static const double barlineSeparation = 0.4;
  static const double beamSpacing = 0.25;
  static const double beamThickness = 0.5;
  static const double bracketThickness = 0.5;
  static const double dashedBarlineDashLength = 0.5;
  static const double dashedBarlineGapLength = 0.25;
  static const double dashedBarlineThickness = 0.16;
  static const double hBarThickness = 1.0;
  static const double hairpinThickness = 0.16;
  static const double legerLineExtension = 0.4;
  static const double legerLineThickness = 0.16;
  static const double lyricLineThickness = 0.16;
  static const double octaveLineThickness = 0.16;
  static const double pedalLineThickness = 0.16;
  static const double repeatBarlineDotSeparation = 0.16;
  static const double repeatEndingLineThickness = 0.16;
  static const double slurEndpointThickness = 0.1;
  static const double slurMidpointThickness = 0.22;
  static const double staffLineThickness = 0.13;
  static const double stemThickness = 0.12;
  static const double subBracketThickness = 0.16;
  static const double textEnclosureThickness = 0.16;
  static const double thickBarlineThickness = 0.5;
  static const double thinBarlineThickness = 0.16;
  static const double thinThickBarlineSeparation = 0.4;
  static const double tieEndpointThickness = 0.1;
  static const double tieMidpointThickness = 0.22;
  static const double tupletBracketThickness = 0.16;
}

/// Every glyph the renderer knows how to draw, by SMuFL name.
class Smufl {
  static const noteheadDoubleWhole = Glyph('noteheadDoubleWhole', '\u{E0A0}', 2.396, 0.0, 2.396, 0.62, -0.62, stemUpSE: [2.036, 0.004], stemDownNW: [0.36, 0.004]);
  static const noteheadWhole = Glyph('noteheadWhole', '\u{E0A2}', 1.688, 0.0, 1.688, 0.5, -0.5);
  static const noteheadHalf = Glyph('noteheadHalf', '\u{E0A3}', 1.18, 0.0, 1.18, 0.5, -0.5, stemUpSE: [1.18, 0.168], stemDownNW: [0.0, -0.168]);
  static const noteheadBlack = Glyph('noteheadBlack', '\u{E0A4}', 1.18, 0.0, 1.18, 0.5, -0.5, stemUpSE: [1.18, 0.168], stemDownNW: [0.0, -0.168]);
  static const noteheadXWhole = Glyph('noteheadXWhole', '\u{E0A7}', 1.508, 0.0, 1.508, 0.5, -0.5);
  static const noteheadXHalf = Glyph('noteheadXHalf', '\u{E0A8}', 1.336, 0.0, 1.336, 0.5, -0.5, stemUpSE: [1.336, 0.412], stemDownNW: [0.0, -0.412]);
  static const noteheadXBlack = Glyph('noteheadXBlack', '\u{E0A9}', 1.16, 0.0, 1.16, 0.5, -0.5, stemUpSE: [1.16, 0.444], stemDownNW: [0.0, -0.44]);
  static const noteheadDiamondWhole = Glyph('noteheadDiamondWhole', '\u{E0D8}', 1.832, -0.001, 1.829, 0.619, -0.62);
  static const noteheadDiamondHalf = Glyph('noteheadDiamondHalf', '\u{E0D9}', 1.28, 0.0, 1.28, 0.74, -0.736, stemUpSE: [1.28, 0.0], stemDownNW: [0.0, 0.0]);
  static const noteheadDiamondBlack = Glyph('noteheadDiamondBlack', '\u{E0DB}', 1.28, 0.0, 1.28, 0.74, -0.736, stemUpSE: [1.28, 0.0], stemDownNW: [0.0, 0.0]);
  static const noteheadSlashHorizontalEnds = Glyph('noteheadSlashHorizontalEnds', '\u{E101}', 2.124, 0.0, 2.12, 1.0, -1.0, stemUpSE: [2.12, 1.0], stemDownNW: [0.0, -1.0]);
  static const noteheadTriangleUpBlack = Glyph('noteheadTriangleUpBlack', '\u{E0BE}', 1.172, 0.0, 1.172, 0.5, -0.5, stemUpSE: [1.172, -0.5], stemDownNW: [0.0, -0.5]);
  static const restMaxima = Glyph('restMaxima', '\u{E4E0}', 1.524, 0.0, 1.524, 1.0, -0.996);
  static const restLonga = Glyph('restLonga', '\u{E4E1}', 0.5, 0.0, 0.5, 1.0, -0.996);
  static const restDoubleWhole = Glyph('restDoubleWhole', '\u{E4E2}', 0.504, 0.0, 0.5, 1.0, 0.0);
  static const restWhole = Glyph('restWhole', '\u{E4E3}', 1.132, 0.0, 1.128, 0.036, -0.54);
  static const restHalf = Glyph('restHalf', '\u{E4E4}', 1.132, 0.0, 1.128, 0.568, -0.008);
  static const restQuarter = Glyph('restQuarter', '\u{E4E5}', 1.08, 0.004, 1.08, 1.492, -1.5);
  static const rest8th = Glyph('rest8th', '\u{E4E6}', 1.0, 0.0, 0.988, 0.696, -1.004);
  static const rest16th = Glyph('rest16th', '\u{E4E7}', 1.28, 0.0, 1.28, 0.716, -2.0);
  static const rest32nd = Glyph('rest32nd', '\u{E4E8}', 1.452, 0.0, 1.452, 1.704, -2.0);
  static const rest64th = Glyph('rest64th', '\u{E4E9}', 1.696, 0.0, 1.692, 1.72, -3.012);
  static const rest128th = Glyph('rest128th', '\u{E4EA}', 1.94, 0.0, 1.94, 2.756, -3.0);
  static const flag8thUp = Glyph('flag8thUp', '\u{E240}', 1.056, 0.0, 1.056, 0.036, -3.24);
  static const flag8thDown = Glyph('flag8thDown', '\u{E241}', 1.224, 0.0, 1.224, 3.232, -0.056);
  static const flag16thUp = Glyph('flag16thUp', '\u{E242}', 1.116, 0.0, 1.116, 0.008, -3.252);
  static const flag16thDown = Glyph('flag16thDown', '\u{E243}', 1.168, 0.0, 1.164, 3.248026, -0.036);
  static const flag32ndUp = Glyph('flag32ndUp', '\u{E244}', 1.048, 0.0, 1.044, 0.596, -3.248);
  static const flag32ndDown = Glyph('flag32ndDown', '\u{E245}', 1.096, 0.0, 1.092, 3.248, -0.688);
  static const flag64thUp = Glyph('flag64thUp', '\u{E246}', 1.048, 0.0, 1.044, 1.388, -3.248);
  static const flag64thDown = Glyph('flag64thDown', '\u{E247}', 1.1, 0.0, 1.092, 3.248, -1.504);
  static const flag128thUp = Glyph('flag128thUp', '\u{E248}', 1.036, 0.0, 1.044, 2.132, -3.248);
  static const flag128thDown = Glyph('flag128thDown', '\u{E249}', 1.1, 0.0, 1.092, 3.248, -2.32);
  static const accidentalDoubleFlat = Glyph('accidentalDoubleFlat', '\u{E264}', 1.652, 0.0, 1.644, 1.748, -0.7);
  static const accidentalFlat = Glyph('accidentalFlat', '\u{E260}', 0.904, 0.0, 0.904, 1.756, -0.7);
  static const accidentalNatural = Glyph('accidentalNatural', '\u{E261}', 0.672, 0.0, 0.672, 1.364, -1.34);
  static const accidentalSharp = Glyph('accidentalSharp', '\u{E262}', 0.996, 0.0, 0.996, 1.4, -1.392);
  static const accidentalDoubleSharp = Glyph('accidentalDoubleSharp', '\u{E263}', 1.0, 0.0, 0.988, 0.508, -0.5);
  static const accidentalQuarterToneFlatStein = Glyph('accidentalQuarterToneFlatStein', '\u{E280}', 0.908, 0.004, 0.908, 1.756, -0.7);
  static const accidentalQuarterToneSharpStein = Glyph('accidentalQuarterToneSharpStein', '\u{E282}', 0.716, 0.0, 0.716, 1.228, -1.412);
  static const gClef = Glyph('gClef', '\u{E050}', 2.684, 0.0, 2.684, 4.392, -2.632);
  static const gClef8va = Glyph('gClef8va', '\u{E053}', 2.684, 0.0, 2.684, 5.28, -2.632);
  static const gClef8vb = Glyph('gClef8vb', '\u{E052}', 2.656, 0.0, 2.684, 4.392, -3.512);
  static const gClef15ma = Glyph('gClef15ma', '\u{E054}', 2.684, 0.0, 2.684, 5.276, -2.632);
  static const gClef15mb = Glyph('gClef15mb', '\u{E051}', 2.684, 0.0, 2.684, 4.392, -3.524);
  static const fClef = Glyph('fClef', '\u{E062}', 2.736, -0.02, 2.736, 1.048, -2.54);
  static const fClef8va = Glyph('fClef8va', '\u{E065}', 2.736, -0.02, 2.736, 1.98, -2.54);
  static const fClef8vb = Glyph('fClef8vb', '\u{E064}', 2.736, -0.02, 2.736, 1.048, -2.976);
  static const fClef15ma = Glyph('fClef15ma', '\u{E066}', 2.736, -0.02, 2.736, 1.984, -2.54);
  static const fClef15mb = Glyph('fClef15mb', '\u{E063}', 2.736, -0.02, 2.736, 1.048, -2.968);
  static const cClef = Glyph('cClef', '\u{E05C}', 2.796, 0.0, 2.796, 2.024, -2.024);
  static const cClef8vb = Glyph('cClef8vb', '\u{E05D}', 2.796, 0.0, 2.796, 2.024, -2.964);
  static const unpitchedPercussionClef1 = Glyph('unpitchedPercussionClef1', '\u{E069}', 1.528, 0.0, 1.528, 1.0, -1.0);
  static const sixStringTabClef = Glyph('6stringTabClef', '\u{E06D}', 1.636, -0.012, 1.632, 3.056, -2.992);
  static const timeSig0 = Glyph('timeSig0', '\u{E080}', 1.88, 0.08, 1.8, 1.004, -1.0);
  static const timeSig1 = Glyph('timeSig1', '\u{E081}', 1.336, 0.08, 1.256, 1.004, -1.0);
  static const timeSig2 = Glyph('timeSig2', '\u{E082}', 1.784, 0.08, 1.704, 1.016, -1.028);
  static const timeSig3 = Glyph('timeSig3', '\u{E083}', 1.684, 0.08, 1.604, 0.996, -1.004);
  static const timeSig4 = Glyph('timeSig4', '\u{E084}', 1.88, 0.08, 1.8, 1.004, -1.0);
  static const timeSig5 = Glyph('timeSig5', '\u{E085}', 1.612, 0.08, 1.532, 0.984, -1.004);
  static const timeSig6 = Glyph('timeSig6', '\u{E086}', 1.736, 0.08, 1.656, 1.004, -0.996);
  static const timeSig7 = Glyph('timeSig7', '\u{E087}', 1.764, 0.08, 1.684, 0.996, -1.0);
  static const timeSig8 = Glyph('timeSig8', '\u{E088}', 1.744, 0.08, 1.664, 1.036, -1.036);
  static const timeSig9 = Glyph('timeSig9', '\u{E089}', 1.736, 0.08, 1.656, 1.004, -0.996);
  static const timeSigCommon = Glyph('timeSigCommon', '\u{E08A}', 1.696, 0.02, 1.696, 1.004, -0.996);
  static const timeSigCutCommon = Glyph('timeSigCutCommon', '\u{E08B}', 1.668, 0.0, 1.672, 1.444, -1.436);
  static const timeSigPlus = Glyph('timeSigPlus', '\u{E08C}', 2.0, -0.004, 1.996, 1.0, -1.0);
  static const augmentationDot = Glyph('augmentationDot', '\u{E1E7}', 0.4, 0.0, 0.4, 0.2, -0.2);
  static const brace = Glyph('brace', '\u{E000}', 0.28, 0.0, 0.277415, 4.00244, -0.002531);
  static const bracketTop = Glyph('bracketTop', '\u{E003}', 1.876, 0.0, 1.876, 1.18, 0.0);
  static const bracketBottom = Glyph('bracketBottom', '\u{E004}', 1.876, 0.0, 1.876, 0.0, -1.18);
  static const repeatDot = Glyph('repeatDot', '\u{E044}', 0.4, 0.0, 0.4, 0.2, -0.2);
  static const articAccentAbove = Glyph('articAccentAbove', '\u{E4A0}', 1.356, 0.0, 1.356, 0.98, 0.004);
  static const articAccentBelow = Glyph('articAccentBelow', '\u{E4A1}', 1.356, 0.0, 1.356, 0.0, -0.976);
  static const articStaccatoAbove = Glyph('articStaccatoAbove', '\u{E4A2}', 0.336, 0.0, 0.336, 0.336, 0.0);
  static const articStaccatoBelow = Glyph('articStaccatoBelow', '\u{E4A3}', 0.336, 0.0, 0.336, 0.0, -0.336);
  static const articTenutoAbove = Glyph('articTenutoAbove', '\u{E4A4}', 1.352, -0.004, 1.352, 0.192, 0.0);
  static const articTenutoBelow = Glyph('articTenutoBelow', '\u{E4A5}', 1.352, -0.004, 1.352, 0.0, -0.192);
  static const articMarcatoAbove = Glyph('articMarcatoAbove', '\u{E4AC}', 0.944, -0.004, 0.94, 1.012, -0.004);
  static const articMarcatoBelow = Glyph('articMarcatoBelow', '\u{E4AD}', 0.944, -0.004, 0.94, 0.0, -1.016);
  static const articStaccatissimoAbove = Glyph('articStaccatissimoAbove', '\u{E4A6}', 0.408, 0.004, 0.4, 1.172, -0.008);
  static const articStaccatissimoBelow = Glyph('articStaccatissimoBelow', '\u{E4A7}', 0.408, 0.004, 0.4, 0.0, -1.18);
  static const fermataAbove = Glyph('fermataAbove', '\u{E4C0}', 2.42, 0.012, 2.42, 1.316, -0.012);
  static const fermataBelow = Glyph('fermataBelow', '\u{E4C1}', 2.42, 0.012, 2.42, 0.0, -1.328);
  static const ornamentTrill = Glyph('ornamentTrill', '\u{E566}', 2.084, 0.0, 2.084, 1.56, -0.04);
  static const ornamentMordent = Glyph('ornamentMordent', '\u{E56D}', 2.916, 0.004, 2.916, 1.276, -0.292);
  static const ornamentShortTrill = Glyph('ornamentShortTrill', '\u{E56C}', 2.92, 0.0, 2.9, 0.98, 0.0);
  static const ornamentTurn = Glyph('ornamentTurn', '\u{E567}', 1.84, 0.0, 1.84, 0.872, 0.0);
  static const segno = Glyph('segno', '\u{E047}', 2.228, 0.016, 2.2, 3.036, -0.108);
  static const coda = Glyph('coda', '\u{E048}', 3.816, -0.016, 3.82, 3.592, -0.632);
  static const dynamicPiano = Glyph('dynamicPiano', '\u{E520}', 1.46, -0.356, 1.464, 1.096, -0.568);
  static const dynamicMezzo = Glyph('dynamicMezzo', '\u{E521}', 1.748, -0.08, 1.784, 1.096, -0.04);
  static const dynamicForte = Glyph('dynamicForte', '\u{E522}', 1.456, -0.564, 1.456, 1.776, -0.608);
  static const dynamicRinforzando = Glyph('dynamicRinforzando', '\u{E523}', 1.108, -0.08, 1.108, 1.096, 0.0);
  static const dynamicSforzando = Glyph('dynamicSforzando', '\u{E524}', 0.916, 0.0, 0.916, 1.092, -0.04);
  static const dynamicZ = Glyph('dynamicZ', '\u{E525}', 0.976, -0.12, 0.976, 1.072, -0.04);
  static const dynamicNiente = Glyph('dynamicNiente', '\u{E526}', 1.232, -0.092, 1.232, 1.096, -0.04);
  static const keyboardPedalPed = Glyph('keyboardPedalPed', '\u{E650}', 4.076, 0.0, 4.076, 2.22, -0.032);
  static const keyboardPedalUp = Glyph('keyboardPedalUp', '\u{E655}', 1.8, 0.0, 1.8, 1.8, 0.0);
  static const tuplet0 = Glyph('tuplet0', '\u{E880}', 1.276, 0.0, 1.272, 1.5, -0.032);
  static const tuplet1 = Glyph('tuplet1', '\u{E881}', 0.984, 0.04, 1.024, 1.488, 0.0);
  static const tuplet2 = Glyph('tuplet2', '\u{E882}', 1.276, 0.04, 1.316, 1.5, -0.024);
  static const tuplet3 = Glyph('tuplet3', '\u{E883}', 1.184, 0.04, 1.224, 1.5, -0.032);
  static const tuplet4 = Glyph('tuplet4', '\u{E884}', 1.212, 0.04, 1.252, 1.488, 0.0);
  static const tuplet5 = Glyph('tuplet5', '\u{E885}', 1.268, 0.04, 1.308, 1.492, -0.032);
  static const tuplet6 = Glyph('tuplet6', '\u{E886}', 1.216, 0.04, 1.256, 1.5, -0.032);
  static const tuplet7 = Glyph('tuplet7', '\u{E887}', 1.212, 0.12, 1.332, 1.488, -0.016);
  static const tuplet8 = Glyph('tuplet8', '\u{E888}', 1.252, 0.04, 1.292, 1.5, -0.032);
  static const tuplet9 = Glyph('tuplet9', '\u{E889}', 1.216, 0.04, 1.256, 1.5, -0.032);
  static const tupletColon = Glyph('tupletColon', '\u{E88A}', 0.444, 0.04, 0.484, 1.072, 0.232);
  static const arpeggiatoUp = Glyph('arpeggiatoUp', '\u{E634}', 0.912, 0.004, 0.916, 6.044, 0.028);
  static const tremolo1 = Glyph('tremolo1', '\u{E220}', 0.6, -0.6, 0.6, 0.376, -0.372);
  static const tremolo2 = Glyph('tremolo2', '\u{E221}', 0.596, -0.604, 0.596, 0.748, -0.748);
  static const tremolo3 = Glyph('tremolo3', '\u{E222}', 0.6, -0.6, 0.6, 1.112, -1.12);

  /// Looks a glyph up by its SMuFL name. `null` when it is not one of the
  /// glyphs carried over here, which is the renderer's cue to draw nothing
  /// rather than to draw the wrong thing.
  static Glyph? byName(String name) => _byName[name];

  static const Map<String, Glyph> _byName = {
    'noteheadDoubleWhole': noteheadDoubleWhole,
    'noteheadWhole': noteheadWhole,
    'noteheadHalf': noteheadHalf,
    'noteheadBlack': noteheadBlack,
    'noteheadXWhole': noteheadXWhole,
    'noteheadXHalf': noteheadXHalf,
    'noteheadXBlack': noteheadXBlack,
    'noteheadDiamondWhole': noteheadDiamondWhole,
    'noteheadDiamondHalf': noteheadDiamondHalf,
    'noteheadDiamondBlack': noteheadDiamondBlack,
    'noteheadSlashHorizontalEnds': noteheadSlashHorizontalEnds,
    'noteheadTriangleUpBlack': noteheadTriangleUpBlack,
    'restMaxima': restMaxima,
    'restLonga': restLonga,
    'restDoubleWhole': restDoubleWhole,
    'restWhole': restWhole,
    'restHalf': restHalf,
    'restQuarter': restQuarter,
    'rest8th': rest8th,
    'rest16th': rest16th,
    'rest32nd': rest32nd,
    'rest64th': rest64th,
    'rest128th': rest128th,
    'flag8thUp': flag8thUp,
    'flag8thDown': flag8thDown,
    'flag16thUp': flag16thUp,
    'flag16thDown': flag16thDown,
    'flag32ndUp': flag32ndUp,
    'flag32ndDown': flag32ndDown,
    'flag64thUp': flag64thUp,
    'flag64thDown': flag64thDown,
    'flag128thUp': flag128thUp,
    'flag128thDown': flag128thDown,
    'accidentalDoubleFlat': accidentalDoubleFlat,
    'accidentalFlat': accidentalFlat,
    'accidentalNatural': accidentalNatural,
    'accidentalSharp': accidentalSharp,
    'accidentalDoubleSharp': accidentalDoubleSharp,
    'accidentalQuarterToneFlatStein': accidentalQuarterToneFlatStein,
    'accidentalQuarterToneSharpStein': accidentalQuarterToneSharpStein,
    'gClef': gClef,
    'gClef8va': gClef8va,
    'gClef8vb': gClef8vb,
    'gClef15ma': gClef15ma,
    'gClef15mb': gClef15mb,
    'fClef': fClef,
    'fClef8va': fClef8va,
    'fClef8vb': fClef8vb,
    'fClef15ma': fClef15ma,
    'fClef15mb': fClef15mb,
    'cClef': cClef,
    'cClef8vb': cClef8vb,
    'unpitchedPercussionClef1': unpitchedPercussionClef1,
    '6stringTabClef': sixStringTabClef,
    'timeSig0': timeSig0,
    'timeSig1': timeSig1,
    'timeSig2': timeSig2,
    'timeSig3': timeSig3,
    'timeSig4': timeSig4,
    'timeSig5': timeSig5,
    'timeSig6': timeSig6,
    'timeSig7': timeSig7,
    'timeSig8': timeSig8,
    'timeSig9': timeSig9,
    'timeSigCommon': timeSigCommon,
    'timeSigCutCommon': timeSigCutCommon,
    'timeSigPlus': timeSigPlus,
    'augmentationDot': augmentationDot,
    'brace': brace,
    'bracketTop': bracketTop,
    'bracketBottom': bracketBottom,
    'repeatDot': repeatDot,
    'articAccentAbove': articAccentAbove,
    'articAccentBelow': articAccentBelow,
    'articStaccatoAbove': articStaccatoAbove,
    'articStaccatoBelow': articStaccatoBelow,
    'articTenutoAbove': articTenutoAbove,
    'articTenutoBelow': articTenutoBelow,
    'articMarcatoAbove': articMarcatoAbove,
    'articMarcatoBelow': articMarcatoBelow,
    'articStaccatissimoAbove': articStaccatissimoAbove,
    'articStaccatissimoBelow': articStaccatissimoBelow,
    'fermataAbove': fermataAbove,
    'fermataBelow': fermataBelow,
    'ornamentTrill': ornamentTrill,
    'ornamentMordent': ornamentMordent,
    'ornamentShortTrill': ornamentShortTrill,
    'ornamentTurn': ornamentTurn,
    'segno': segno,
    'coda': coda,
    'dynamicPiano': dynamicPiano,
    'dynamicMezzo': dynamicMezzo,
    'dynamicForte': dynamicForte,
    'dynamicRinforzando': dynamicRinforzando,
    'dynamicSforzando': dynamicSforzando,
    'dynamicZ': dynamicZ,
    'dynamicNiente': dynamicNiente,
    'keyboardPedalPed': keyboardPedalPed,
    'keyboardPedalUp': keyboardPedalUp,
    'tuplet0': tuplet0,
    'tuplet1': tuplet1,
    'tuplet2': tuplet2,
    'tuplet3': tuplet3,
    'tuplet4': tuplet4,
    'tuplet5': tuplet5,
    'tuplet6': tuplet6,
    'tuplet7': tuplet7,
    'tuplet8': tuplet8,
    'tuplet9': tuplet9,
    'tupletColon': tupletColon,
    'arpeggiatoUp': arpeggiatoUp,
    'tremolo1': tremolo1,
    'tremolo2': tremolo2,
    'tremolo3': tremolo3,
  };
}
