name: score
description: 'An application to search through my sheet music.'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  ansicolor: '>=2.0.0 <3.0.0'
  auto_route: '>=10.0.0 <11.0.0'
  behaviour: '>=3.0.0 <4.0.0'
  flutter:
    sdk: flutter
  flutter_fox_logging: '>=2.0.0 <3.0.0'
  flutter_localizations:
    sdk: flutter
  get_it: '>=8.0.0 <9.0.0'
  grpc: '>=4.0.0 <5.0.0'
  hive_ce: '>=2.0.0 <3.0.0'
  hive_ce_flutter:
  infinite_scroll_pagination: '>=5.0.0 <6.0.0'
  intl:
  oidc: '>0.0.0 <1.0.0'
  path_provider: '>=2.1.5 <3.0.0'
  protobuf: '>=3.0.0 <4.0.0'

dev_dependencies:
  auto_route_generator:
  build_runner:
  flutter_test:
    sdk: flutter
  hive_ce_generator:
  lint:

flutter:
  uses-material-design: true

  assets:
    - assets/music_xml_viewer/