name: score
description: 'An application to search through my sheet music.'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  ansicolor: '>=2.0.0 <3.0.0'
  auto_route: '>=9.0.0 <10.0.0'
  behaviour: '>=3.0.0 <4.0.0'
  cbl:
  cbl_flutter: '>=3.2.0 <4.0.0'
  cbl_flutter_ce:
  flutter:
    sdk: flutter
  flutter_fox_logging: '>=2.0.0 <3.0.0'
  flutter_localizations:
    sdk: flutter
  get_it: '>=7.0.0 <8.0.0'
  grpc: '>=4.0.0 <5.0.0'
  hive_ce:
  hive_ce_flutter: '>=2.0.0 <3.0.0'
  infinite_scroll_pagination: '>=4.1.0 <5.0.0'
  intl:
  isolated: '>=1.0.0 <2.0.0'
  oidc: '>0.0.0 <1.0.0'
  protobuf: '>3.0.0 <4.0.0'

dev_dependencies:
  auto_route_generator:
  build_runner:
  cbl_generator:
  flutter_test:
    sdk: flutter
  hive_ce_generator:
  lint:

flutter:
  generate: true
  uses-material-design: true
