version: '3.9'

services:
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - "7701:5432"
    env_file:
      - .env
    volumes:
      - ./.dev/postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "7702:8080"

  meilisearch:
    image: getmeili/meilisearch:latest
    ports:
      - "7703:7700"
    env_file:
      - .env
    volumes:
      - ./.dev/meilisearch/data.ms:/data.ms
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7700"]
      interval: 10s
      timeout: 5s
      retries: 5

