#!/usr/bin/env python3
"""Writes lib/notation/render/smufl.dart out of the Bravura metadata.

Only the glyphs the renderer actually draws are carried over: the whole
metadata file is 1.2MB and all but a few hundred bytes of it is about notation
this does not draw yet.
"""
import json, sys

names = json.load(open('glyphnames.json'))
meta = json.load(open('Bravura.json'))
adv = meta['glyphAdvanceWidths']
bbox = meta['glyphBBoxes']
anchors = meta['glyphsWithAnchors']

WANTED = [
    # noteheads
    'noteheadDoubleWhole', 'noteheadWhole', 'noteheadHalf', 'noteheadBlack',
    'noteheadXWhole', 'noteheadXHalf', 'noteheadXBlack',
    'noteheadDiamondWhole', 'noteheadDiamondHalf', 'noteheadDiamondBlack',
    'noteheadSlashHorizontalEnds', 'noteheadTriangleUpBlack',
    # rests
    'restMaxima', 'restLonga', 'restDoubleWhole', 'restWhole', 'restHalf',
    'restQuarter', 'rest8th', 'rest16th', 'rest32nd', 'rest64th', 'rest128th',
    # flags
    'flag8thUp', 'flag8thDown', 'flag16thUp', 'flag16thDown',
    'flag32ndUp', 'flag32ndDown', 'flag64thUp', 'flag64thDown',
    'flag128thUp', 'flag128thDown',
    # accidentals
    'accidentalDoubleFlat', 'accidentalFlat', 'accidentalNatural',
    'accidentalSharp', 'accidentalDoubleSharp',
    'accidentalQuarterToneFlatStein', 'accidentalQuarterToneSharpStein',
    # clefs
    'gClef', 'gClef8va', 'gClef8vb', 'gClef15ma', 'gClef15mb',
    'fClef', 'fClef8va', 'fClef8vb', 'fClef15ma', 'fClef15mb',
    'cClef', 'cClef8vb', 'unpitchedPercussionClef1', '6stringTabClef',
    # time signatures
    'timeSig0', 'timeSig1', 'timeSig2', 'timeSig3', 'timeSig4',
    'timeSig5', 'timeSig6', 'timeSig7', 'timeSig8', 'timeSig9',
    'timeSigCommon', 'timeSigCutCommon', 'timeSigPlus',
    # dots, brackets, braces
    'augmentationDot', 'brace', 'bracketTop', 'bracketBottom',
    'repeatDot',
    # articulations
    'articAccentAbove', 'articAccentBelow',
    'articStaccatoAbove', 'articStaccatoBelow',
    'articTenutoAbove', 'articTenutoBelow',
    'articMarcatoAbove', 'articMarcatoBelow',
    'articStaccatissimoAbove', 'articStaccatissimoBelow',
    # ornaments and holds
    'fermataAbove', 'fermataBelow',
    'ornamentTrill', 'ornamentMordent', 'ornamentShortTrill', 'ornamentTurn',
    'segno', 'coda',
    # dynamics, built a letter at a time
    'dynamicPiano', 'dynamicMezzo', 'dynamicForte', 'dynamicRinforzando',
    'dynamicSforzando', 'dynamicZ', 'dynamicNiente',
    # pedal
    'keyboardPedalPed', 'keyboardPedalUp',
    # tuplet digits
    'tuplet0', 'tuplet1', 'tuplet2', 'tuplet3', 'tuplet4',
    'tuplet5', 'tuplet6', 'tuplet7', 'tuplet8', 'tuplet9', 'tupletColon',
    # arpeggio / tremolo
    'arpeggiatoUp', 'tremolo1', 'tremolo2', 'tremolo3',
]


# A few SMuFL names are not Dart identifiers, because they begin with a digit.
RENAMES = {
    '6stringTabClef': 'sixStringTabClef',
}


def dart_name(n):
    """A SMuFL name as a Dart identifier."""
    return RENAMES.get(n, n)


def esc(cp):
    """A codepoint as a Dart string literal."""
    return '\\u{%s}' % cp[2:]


missing = [n for n in WANTED if n not in names]
if missing:
    print('not in glyphnames.json: %s' % missing, file=sys.stderr)

out = []
w = out.append
w('// GENERATED by scripts/gen_smufl.py from the Bravura metadata. Do not edit.')
w('//')
w('// Bravura is (c) Steinberg Media Technologies GmbH, under the SIL Open Font')
w('// License 1.1. Only the glyphs this renderer draws are carried over here.')
w('')
w('/// One glyph of the music font: what to draw it with, and how much room it')
w('/// takes. Every measurement is in staff spaces, which is how the metadata')
w('/// states them and how the layout thinks.')
w('class Glyph {')
w('  const Glyph(this.name, this.char, this.advance, this.left, this.right,')
w('      this.top, this.bottom, {this.stemUpSE, this.stemDownNW});')
w('')
w('  /// The SMuFL name, which is what the metadata calls it.')
w('  final String name;')
w('')
w('  /// The character to set in Bravura to get it.')
w('  final String char;')
w('')
w('  /// How far the pen moves after drawing it.')
w('  final double advance;')
w('')
w('  /// The box it actually covers, measured from the origin. Up is positive')
w('  /// here, the way the font states it; the renderer flips it.')
w('  final double left;')
w('  final double right;')
w('  final double top;')
w('  final double bottom;')
w('')
w('  /// Where a stem meets it, when it is a notehead. Up-stems attach on the')
w('  /// right, down-stems on the left, and neither sits exactly at the corner —')
w('  /// which is why these are read rather than guessed.')
w('  final List<double>? stemUpSE;')
w('  final List<double>? stemDownNW;')
w('')
w('  double get width => right - left;')
w('  double get height => top - bottom;')
w('')
w('  @override')
w('  String toString() => \'Glyph($name)\';')
w('}')
w('')
w('/// How thick the lines of the engraving are, as the font says they should')
w('/// be. Everything drawn as a shape rather than as a glyph — staff lines,')
w('/// stems, beams, barlines, ties — is drawn to these.')
w('class EngravingDefaults {')
for k in sorted(meta['engravingDefaults']):
    v = meta['engravingDefaults'][k]
    if isinstance(v, (int, float)):
        w('  static const double %s = %s;' % (k, float(v)))
w('}')
w('')
w('/// Every glyph the renderer knows how to draw, by SMuFL name.')
w('class Smufl {')

for n in WANTED:
    if n not in names:
        continue
    cp = names[n]['codepoint']
    a = adv.get(n, 0.0)
    b = bbox.get(n, {'bBoxNE': [0, 0], 'bBoxSW': [0, 0]})
    ne, sw = b['bBoxNE'], b['bBoxSW']
    an = anchors.get(n, {})
    extra = ''
    if 'stemUpSE' in an:
        extra += ', stemUpSE: [%s, %s]' % (float(an['stemUpSE'][0]), float(an['stemUpSE'][1]))
    if 'stemDownNW' in an:
        extra += ', stemDownNW: [%s, %s]' % (float(an['stemDownNW'][0]), float(an['stemDownNW'][1]))
    w("  static const %s = Glyph('%s', '%s', %s, %s, %s, %s, %s%s);"
      % (dart_name(n), n, esc(cp), float(a), float(sw[0]), float(ne[0]),
         float(ne[1]), float(sw[1]), extra))

w('')
w('  /// Looks a glyph up by its SMuFL name. `null` when it is not one of the')
w('  /// glyphs carried over here, which is the renderer\'s cue to draw nothing')
w('  /// rather than to draw the wrong thing.')
w('  static Glyph? byName(String name) => _byName[name];')
w('')
w('  static const Map<String, Glyph> _byName = {')
for n in WANTED:
    if n not in names:
        continue
    w("    '%s': %s," % (n, dart_name(n)))
w('  };')
w('}')
w('')

open(sys.argv[1], 'w').write('\n'.join(out))
print('wrote %s (%d glyphs)' % (sys.argv[1], len([n for n in WANTED if n in names])))
