name: score_backend
description: A sample command-line application with basic argument parsing.
version: 0.0.1
repository: https://github.com/wim07101993/score/
publish_to: none

environment:
  sdk: ^3.2.3

dependencies:
  args: ^2.4.2
  xml: ">=6.5.0 <7.0.0"

dev_dependencies:
  lint: ^2.0.0
  test: ^1.24.0
