// Code generated by ogen, DO NOT EDIT.
package api

type DeleteCollectionEntryRes interface {
	deleteCollectionEntryRes()
}

type DeleteCollectionRes interface {
	deleteCollectionRes()
}

type DeleteSetEntryRes interface {
	deleteSetEntryRes()
}

type DeleteSetRes interface {
	deleteSetRes()
}

type GetCollectionRes interface {
	getCollectionRes()
}

type GetScoreRes interface {
	getScoreRes()
}

type GetSetRes interface {
	getSetRes()
}

type HealthzRes interface {
	healthzRes()
}

type ListCollectionsRes interface {
	listCollectionsRes()
}

type ListScoresRes interface {
	listScoresRes()
}

type ListSetsRes interface {
	listSetsRes()
}

type PutCollectionEntryRes interface {
	putCollectionEntryRes()
}

type PutCollectionEntryViewRes interface {
	putCollectionEntryViewRes()
}

type PutCollectionRes interface {
	putCollectionRes()
}

type PutScoreReq interface {
	putScoreReq()
}

type PutScoreRes interface {
	putScoreRes()
}

type PutSetEntryRes interface {
	putSetEntryRes()
}

type PutSetEntryViewRes interface {
	putSetEntryViewRes()
}

type PutSetRes interface {
	putSetRes()
}
