// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// GetScore implements getScore operation.
	//
	// Returns either the metadata of the score or the MusicXML document it was extracted from, whichever
	// the `Accept` header asks for. Anything that is not one of the MusicXML media types is answered with
	// the JSON metadata.
	//
	// Requires the `score_viewer` role for both representations: the document is not a way around the role
	// check that protects the metadata.
	//
	// GET /scores/{scoreId}
	GetScore(ctx context.Context, params GetScoreParams) (GetScoreRes, error)
	// Healthz implements healthz operation.
	//
	// Answers `OK` as long as the server is serving. Public.
	//
	// GET /healthz
	Healthz(ctx context.Context, params HealthzParams) (HealthzRes, error)
	// ListScores implements listScores operation.
	//
	// Returns the metadata of every score whose last change falls within the given window, most recently
	// changed first. Both ends of the window are inclusive and both are required: a client synchronises by
	// asking for everything since the moment it last asked.
	//
	// Requires the `score_viewer` role.
	//
	// GET /scores
	ListScores(ctx context.Context, params ListScoresParams) (ListScoresRes, error)
	// PutScore implements putScore operation.
	//
	// Stores the MusicXML document under the given id, replacing whatever was stored under it before, and
	// extracts the metadata the scores are listed by. A document that is not MusicXML, or that carries
	// something the server cannot store such as an unknown instrument, is rejected whole: nothing of it is
	// left behind.
	//
	// Requires the `score_editor` role.
	//
	// PUT /scores/{scoreId}
	PutScore(ctx context.Context, req PutScoreReq, params PutScoreParams) (PutScoreRes, error)
	// NewError creates *XxxUnknownErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *XxxUnknownErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
