// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// DeleteSet implements deleteSet operation.
//
// Marks the set as deleted. It is kept rather than removed, and it keeps turning up in the change
// window with `deleted_at` filled in, so that a client holding a copy learns that it is gone.
//
// Only the owner of a set can delete it. A set that is not there, already deleted, or not the caller's
// is answered the same way.
//
// Requires the `score_viewer` role.
//
// DELETE /sets/{setId}
func (UnimplementedHandler) DeleteSet(ctx context.Context, params DeleteSetParams) (r DeleteSetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetScore implements getScore operation.
//
// Returns either the metadata of the score or the MusicXML document it was extracted from, whichever
// the `Accept` header asks for. Anything that is not one of the MusicXML media types is answered with
// the JSON metadata.
//
// Requires the `score_viewer` role for both representations: the document is not a way around the role
// check that protects the metadata.
//
// GET /scores/{scoreId}
func (UnimplementedHandler) GetScore(ctx context.Context, params GetScoreParams) (r GetScoreRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSet implements getSet operation.
//
// Returns the set, whether the caller owns it or it is shared with them. `is_owner` says which of the
// two it is, and `shared_with` is only filled in for the owner.
//
// Requires the `score_viewer` role.
//
// GET /sets/{setId}
func (UnimplementedHandler) GetSet(ctx context.Context, params GetSetParams) (r GetSetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Healthz implements healthz operation.
//
// Answers `OK` as long as the server is serving. Public.
//
// GET /healthz
func (UnimplementedHandler) Healthz(ctx context.Context, params HealthzParams) (r HealthzRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListScores implements listScores operation.
//
// Returns the metadata of every score whose last change falls within the given window, most recently
// changed first. Both ends of the window are inclusive and both are required: a client synchronises by
// asking for everything since the moment it last asked.
//
// Requires the `score_viewer` role.
//
// GET /scores
func (UnimplementedHandler) ListScores(ctx context.Context, params ListScoresParams) (r ListScoresRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListSets implements listSets operation.
//
// Returns every set the caller owns or that is shared with them whose last change falls within the
// given window, most recently changed first. Both ends of the window are inclusive and both are
// required: a client synchronises by asking for everything since the moment it last asked.
//
// Sets that were deleted within the window are returned too, with `deleted_at` filled in, so that a
// client holding a copy learns that it is gone rather than syncing it back.
//
// Requires the `score_viewer` role. A set names scores but changes nothing about them, so keeping one
// asks no more of a user than reading the scores in it.
//
// GET /sets
func (UnimplementedHandler) ListSets(ctx context.Context, params ListSetsParams) (r ListSetsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PutScore implements putScore operation.
//
// Stores the MusicXML document under the given id, replacing whatever was stored under it before, and
// extracts the metadata the scores are listed by. A document that is not MusicXML, or that carries
// something the server cannot store such as an unknown instrument, is rejected whole: nothing of it is
// left behind.
//
// Requires the `score_editor` role.
//
// PUT /scores/{scoreId}
func (UnimplementedHandler) PutScore(ctx context.Context, req PutScoreReq, params PutScoreParams) (r PutScoreRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PutSet implements putSet operation.
//
// Stores the set under the given id, replacing whatever was stored under it before, and returns it as
// it now reads. A set that is not there yet belongs to whoever creates it; one that is can only be
// written by its owner.
//
// Writing a set that had been deleted brings it back: a client that still has it and edits it is
// saying it should exist.
//
// Requires the `score_viewer` role. A set names scores but changes nothing about them, so building one
// asks no more of a user than reading the scores in it.
//
// PUT /sets/{setId}
func (UnimplementedHandler) PutSet(ctx context.Context, req *WriteSet, params PutSetParams) (r PutSetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *XxxUnknownErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *XxxUnknownErrorStatusCode) {
	r = new(XxxUnknownErrorStatusCode)
	return r
}
