// Code generated by ogen, DO NOT EDIT.

package api

import (
	"fmt"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/validate"
)

func (s ChangeWindowMoment) Validate() error {
	alias := (string)(s)
	if err := (validate.String{
		MinLength:     0,
		MinLengthSet:  false,
		MaxLength:     0,
		MaxLengthSet:  false,
		Email:         false,
		Hostname:      false,
		Regex:         regexMap["^\\d{8}T\\d{6}$"],
		MinNumeric:    0,
		MinNumericSet: false,
		MaxNumeric:    0,
		MaxNumericSet: false,
	}).Validate(string(alias)); err != nil {
		return errors.Wrap(err, "string")
	}
	return nil
}

func (s *GetScoreBadRequest) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *GetScoreForbidden) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *GetScoreNotFound) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *GetScoreUnauthorized) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s GetScoresResponse) Validate() error {
	alias := ([]Score)(s)
	if alias == nil {
		return errors.New("nil is invalid value")
	}
	var failures []validate.FieldError
	for i, elem := range alias {
		if err := func() error {
			if err := elem.Validate(); err != nil {
				return err
			}
			return nil
		}(); err != nil {
			failures = append(failures, validate.FieldError{
				Name:  fmt.Sprintf("[%d]", i),
				Error: err,
			})
		}
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *ListScoresBadRequest) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *ListScoresForbidden) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *ListScoresUnauthorized) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *ProblemDetails) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := (validate.Int{
			MinSet:        true,
			Min:           100,
			MaxSet:        true,
			Max:           599,
			MinExclusive:  false,
			MaxExclusive:  false,
			MultipleOfSet: false,
			MultipleOf:    0,
			Pattern:       nil,
		}).Validate(int64(s.Status)); err != nil {
			return errors.Wrap(err, "int")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "status",
			Error: err,
		})
	}
	if err := func() error {
		if err := s.ErrorCode.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "errorCode",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s ProblemDetailsErrorCode) Validate() error {
	switch s {
	case "invalid_request":
		return nil
	case "invalid_music_xml":
		return nil
	case "invalid_credentials":
		return nil
	case "missing_role":
		return nil
	case "score_not_found":
		return nil
	case "endpoint_not_found":
		return nil
	case "method_not_allowed":
		return nil
	case "unsupported_media_type":
		return nil
	case "internal_error":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *ProblemDetailsStatusCode) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Response.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "Response",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *PutScoreBadRequest) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *PutScoreForbidden) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *PutScoreUnauthorized) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *PutScoreUnsupportedMediaType) Validate() error {
	alias := (*ProblemDetails)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *Score) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Creators.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "creators",
			Error: err,
		})
	}
	if err := func() error {
		if s.Languages == nil {
			return errors.New("nil is invalid value")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "languages",
			Error: err,
		})
	}
	if err := func() error {
		if s.Instruments == nil {
			return errors.New("nil is invalid value")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "instruments",
			Error: err,
		})
	}
	if err := func() error {
		if s.Tags == nil {
			return errors.New("nil is invalid value")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "tags",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *ScoreCreators) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if s.Composers == nil {
			return errors.New("nil is invalid value")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "composers",
			Error: err,
		})
	}
	if err := func() error {
		if s.Lyricists == nil {
			return errors.New("nil is invalid value")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "lyricists",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *XxxUnknownErrorStatusCode) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Response.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "Response",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}
