// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"

	"github.com/go-faster/errors"
	ht "github.com/ogen-go/ogen/http"
)

func encodePutScoreRequest(
	req PutScoreReq,
	r *http.Request,
) error {
	switch req := req.(type) {
	case *PutScoreReqApplicationVndRecordareMusicxml:
		const contentType = "application/vnd.recordare.musicxml"
		body := req
		ht.SetBody(r, body, contentType)
		return nil
	case *PutScoreReqApplicationVndRecordareMusicxmlXML:
		const contentType = "application/vnd.recordare.musicxml+xml"
		body := req
		ht.SetBody(r, body, contentType)
		return nil
	default:
		return errors.Errorf("unexpected request type: %T", req)
	}
}
