// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"
	"time"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// GetScoreParams is parameters of getScore operation.
type GetScoreParams struct {
	// The representation the caller wants back. An operation that answers in more than one media type
	// reads it to decide which; anything it does not recognise is answered in the media type it lists
	// first.
	Accept OptString `json:",omitempty,omitzero"`
	// The id the score is stored under.
	ScoreId uuid.UUID
	// An id a caller ties its own requests together with. The server logs the request under it and answers
	// a failure with it as the `instance` of the problem, so that reporting a failure is enough to find
	// it. A caller that sends nothing, or sends something that is not a uuid, is given one.
	XCorrelationID OptString `json:",omitempty,omitzero"`
}

func unpackGetScoreParams(packed middleware.Parameters) (params GetScoreParams) {
	{
		key := middleware.ParameterKey{
			Name: "Accept",
			In:   "header",
		}
		if v, ok := packed[key]; ok {
			params.Accept = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "scoreId",
			In:   "path",
		}
		params.ScoreId = packed[key].(uuid.UUID)
	}
	{
		key := middleware.ParameterKey{
			Name: "X-Correlation-ID",
			In:   "header",
		}
		if v, ok := packed[key]; ok {
			params.XCorrelationID = v.(OptString)
		}
	}
	return params
}

func decodeGetScoreParams(args [1]string, argsEscaped bool, r *http.Request) (params GetScoreParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: Accept.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "Accept",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotAcceptVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotAcceptVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Accept.SetTo(paramsDotAcceptVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "Accept",
			In:   "header",
			Err:  err,
		}
	}
	// Decode path: scoreId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "scoreId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.ScoreId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "scoreId",
			In:   "path",
			Err:  err,
		}
	}
	// Decode header: X-Correlation-ID.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "X-Correlation-ID",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotXCorrelationIDVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotXCorrelationIDVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.XCorrelationID.SetTo(paramsDotXCorrelationIDVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "X-Correlation-ID",
			In:   "header",
			Err:  err,
		}
	}
	return params, nil
}

// HealthzParams is parameters of healthz operation.
type HealthzParams struct {
	// An id a caller ties its own requests together with. The server logs the request under it and answers
	// a failure with it as the `instance` of the problem, so that reporting a failure is enough to find
	// it. A caller that sends nothing, or sends something that is not a uuid, is given one.
	XCorrelationID OptString `json:",omitempty,omitzero"`
}

func unpackHealthzParams(packed middleware.Parameters) (params HealthzParams) {
	{
		key := middleware.ParameterKey{
			Name: "X-Correlation-ID",
			In:   "header",
		}
		if v, ok := packed[key]; ok {
			params.XCorrelationID = v.(OptString)
		}
	}
	return params
}

func decodeHealthzParams(args [0]string, argsEscaped bool, r *http.Request) (params HealthzParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: X-Correlation-ID.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "X-Correlation-ID",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotXCorrelationIDVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotXCorrelationIDVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.XCorrelationID.SetTo(paramsDotXCorrelationIDVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "X-Correlation-ID",
			In:   "header",
			Err:  err,
		}
	}
	return params, nil
}

// ListScoresParams is parameters of listScores operation.
type ListScoresParams struct {
	// The start of the change window, inclusive.
	ChangesSince time.Time
	// The end of the change window, inclusive.
	ChangesUntil time.Time
	// An id a caller ties its own requests together with. The server logs the request under it and answers
	// a failure with it as the `instance` of the problem, so that reporting a failure is enough to find
	// it. A caller that sends nothing, or sends something that is not a uuid, is given one.
	XCorrelationID OptString `json:",omitempty,omitzero"`
}

func unpackListScoresParams(packed middleware.Parameters) (params ListScoresParams) {
	{
		key := middleware.ParameterKey{
			Name: "Changes-Since",
			In:   "query",
		}
		params.ChangesSince = packed[key].(time.Time)
	}
	{
		key := middleware.ParameterKey{
			Name: "Changes-Until",
			In:   "query",
		}
		params.ChangesUntil = packed[key].(time.Time)
	}
	{
		key := middleware.ParameterKey{
			Name: "X-Correlation-ID",
			In:   "header",
		}
		if v, ok := packed[key]; ok {
			params.XCorrelationID = v.(OptString)
		}
	}
	return params
}

func decodeListScoresParams(args [0]string, argsEscaped bool, r *http.Request) (params ListScoresParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	h := uri.NewHeaderDecoder(r.Header)
	// Decode query: Changes-Since.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "Changes-Since",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToDateTime(val)
				if err != nil {
					return err
				}

				params.ChangesSince = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "Changes-Since",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: Changes-Until.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "Changes-Until",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToDateTime(val)
				if err != nil {
					return err
				}

				params.ChangesUntil = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "Changes-Until",
			In:   "query",
			Err:  err,
		}
	}
	// Decode header: X-Correlation-ID.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "X-Correlation-ID",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotXCorrelationIDVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotXCorrelationIDVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.XCorrelationID.SetTo(paramsDotXCorrelationIDVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "X-Correlation-ID",
			In:   "header",
			Err:  err,
		}
	}
	return params, nil
}

// PutScoreParams is parameters of putScore operation.
type PutScoreParams struct {
	// The id the score is stored under.
	ScoreId uuid.UUID
	// An id a caller ties its own requests together with. The server logs the request under it and answers
	// a failure with it as the `instance` of the problem, so that reporting a failure is enough to find
	// it. A caller that sends nothing, or sends something that is not a uuid, is given one.
	XCorrelationID OptString `json:",omitempty,omitzero"`
}

func unpackPutScoreParams(packed middleware.Parameters) (params PutScoreParams) {
	{
		key := middleware.ParameterKey{
			Name: "scoreId",
			In:   "path",
		}
		params.ScoreId = packed[key].(uuid.UUID)
	}
	{
		key := middleware.ParameterKey{
			Name: "X-Correlation-ID",
			In:   "header",
		}
		if v, ok := packed[key]; ok {
			params.XCorrelationID = v.(OptString)
		}
	}
	return params
}

func decodePutScoreParams(args [1]string, argsEscaped bool, r *http.Request) (params PutScoreParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode path: scoreId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "scoreId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.ScoreId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "scoreId",
			In:   "path",
			Err:  err,
		}
	}
	// Decode header: X-Correlation-ID.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "X-Correlation-ID",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotXCorrelationIDVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotXCorrelationIDVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.XCorrelationID.SetTo(paramsDotXCorrelationIDVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "X-Correlation-ID",
			In:   "header",
			Err:  err,
		}
	}
	return params, nil
}
