// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// DeleteSet implements deleteSet operation.
//
// Marks the set as deleted. It is kept rather than removed, and it keeps turning up in the change
// window with `deleted_at` filled in, so that a client holding a copy learns that it is gone.
//
// Only the owner of a set can delete it. A set that is not there, already deleted, or not the caller's
// is answered the same way.
//
// Requires the `score_viewer` role.
//
// DELETE /sets/{setId}
func (UnimplementedHandler) DeleteSet(ctx context.Context, params DeleteSetParams) (r DeleteSetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteSetEntry implements deleteSetEntry operation.
//
// Removes the entry and closes the running order up around it. What every player said about how they
// look at it goes with it: it was about a song that is no longer played.
//
// Unlike a set, an entry is removed rather than kept as a headstone. A client that is holding a copy
// learns it is gone from the set it is in, which it reads whole.
//
// Only the owner of a set can take an entry out of it. An entry that is not there, is not in the set
// that was named, or is in a set the caller cannot read, are all answered the same way.
//
// Requires the `score_viewer` role.
//
// DELETE /sets/{setId}/entries/{entryId}
func (UnimplementedHandler) DeleteSetEntry(ctx context.Context, params DeleteSetEntryParams) (r DeleteSetEntryRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetScore implements getScore operation.
//
// Returns either the metadata of the score or the MusicXML document it was extracted from, whichever
// the `Accept` header asks for. Anything that is not one of the MusicXML media types is answered with
// the JSON metadata.
//
// Requires the `score_viewer` role for both representations: the document is not a way around the role
// check that protects the metadata.
//
// GET /scores/{scoreId}
func (UnimplementedHandler) GetScore(ctx context.Context, params GetScoreParams) (r GetScoreRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSet implements getSet operation.
//
// Returns the set, whether the caller owns it or it is shared with them. `is_owner` says which of the
// two it is, and `shared_with` is only filled in for the owner.
//
// Requires the `score_viewer` role.
//
// GET /sets/{setId}
func (UnimplementedHandler) GetSet(ctx context.Context, params GetSetParams) (r GetSetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Healthz implements healthz operation.
//
// Answers `OK` as long as the server is serving. Public.
//
// GET /healthz
func (UnimplementedHandler) Healthz(ctx context.Context, params HealthzParams) (r HealthzRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListScores implements listScores operation.
//
// Returns the metadata of every score whose last change falls within the given window, most recently
// changed first. Both ends of the window are inclusive and both are required: a client synchronises by
// asking for everything since the moment it last asked.
//
// Requires the `score_viewer` role.
//
// GET /scores
func (UnimplementedHandler) ListScores(ctx context.Context, params ListScoresParams) (r ListScoresRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListSets implements listSets operation.
//
// Returns every set the caller owns or that is shared with them whose last change falls within the
// given window, most recently changed first. Both ends of the window are inclusive and both are
// required: a client synchronises by asking for everything since the moment it last asked.
//
// Sets that were deleted within the window are returned too, with `deleted_at` filled in, so that a
// client holding a copy learns that it is gone rather than syncing it back.
//
// Requires the `score_viewer` role. A set names scores but changes nothing about them, so keeping one
// asks no more of a user than reading the scores in it.
//
// GET /sets
func (UnimplementedHandler) ListSets(ctx context.Context, params ListSetsParams) (r ListSetsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PutScore implements putScore operation.
//
// Stores the MusicXML document under the given id, replacing whatever was stored under it before, and
// extracts the metadata the scores are listed by. A document that is not MusicXML, or that carries
// something the server cannot store such as an unknown instrument, is rejected whole: nothing of it is
// left behind.
//
// Requires the `score_editor` role.
//
// PUT /scores/{scoreId}
func (UnimplementedHandler) PutScore(ctx context.Context, req PutScoreReq, params PutScoreParams) (r PutScoreRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PutSet implements putSet operation.
//
// Stores the set under the given id, replacing whatever was stored under it before, and returns it as
// it now reads. A set that is not there yet belongs to whoever creates it; one that is can only be
// written by its owner.
//
// Writing a set that had been deleted brings it back: a client that still has it and edits it is
// saying it should exist.
//
// Requires the `score_viewer` role. A set names scores but changes nothing about them, so building one
// asks no more of a user than reading the scores in it.
//
// PUT /sets/{setId}
func (UnimplementedHandler) PutSet(ctx context.Context, req *WriteSet, params PutSetParams) (r PutSetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PutSetEntry implements putSetEntry operation.
//
// Stores the entry under the given id and returns it as it now reads, including where in the running
// order it ended up and how the caller looks at it.
//
// An entry is its own resource because a set is not rewritten to change one song in it: a client that
// added a song sends that song, and a client that is catching up after a gig it spent offline sends
// the songs it changed rather than a running order that may have moved on without it.
//
// The id is the client's to name, and naming it is what lets a player say how they read a song before
// either has reached the server. An id that already belongs to an entry of another set is refused
// rather than taken over: it would point this set's entry at what another set's players said about
// theirs.
//
// Only the owner of a set can write its entries: what the band plays is the set, and the set is
// theirs. How anybody reads it is not — that is `/sets/{setId}/entries/{entryId}/view`, which
// everyone the set is shared with writes for themselves.
//
// Requires the `score_viewer` role.
//
// PUT /sets/{setId}/entries/{entryId}
func (UnimplementedHandler) PutSetEntry(ctx context.Context, req *WriteSetEntry, params PutSetEntryParams) (r PutSetEntryRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PutSetEntryView implements putSetEntryView operation.
//
// Stores the caller's own view of this entry, replacing whatever they had said before, and returns it
// as it now reads.
//
// Anyone who can read the set can write their own view of its entries: it says nothing about the set
// and changes nothing anybody else sees, so it asks no more of a player than reading the set does.
// Being the owner is neither needed nor enough to write somebody else's — there is no way to write a
// view that is not your own.
//
// A set the caller cannot read, and an entry that is not in the set named, are answered the same way
// as one that is not there at all.
//
// Requires the `score_viewer` role.
//
// PUT /sets/{setId}/entries/{entryId}/view
func (UnimplementedHandler) PutSetEntryView(ctx context.Context, req *WriteEntryView, params PutSetEntryViewParams) (r PutSetEntryViewRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *XxxUnknownErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *XxxUnknownErrorStatusCode) {
	r = new(XxxUnknownErrorStatusCode)
	return r
}
