// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetScore implements getScore operation.
//
// Returns either the metadata of the score or the MusicXML document it was extracted from, whichever
// the `Accept` header asks for. Anything that is not one of the MusicXML media types is answered with
// the JSON metadata.
//
// Requires the `score_viewer` role for both representations: the document is not a way around the role
// check that protects the metadata.
//
// GET /scores/{scoreId}
func (UnimplementedHandler) GetScore(ctx context.Context, params GetScoreParams) (r GetScoreRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Healthz implements healthz operation.
//
// Answers `OK` as long as the server is serving. Public.
//
// GET /healthz
func (UnimplementedHandler) Healthz(ctx context.Context) (r HealthzRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListScores implements listScores operation.
//
// Returns the metadata of every score whose last change falls within the given window, most recently
// changed first. Both ends of the window are inclusive and both are required: a client synchronises by
// asking for everything since the moment it last asked.
//
// Requires the `score_viewer` role.
//
// GET /scores
func (UnimplementedHandler) ListScores(ctx context.Context, params ListScoresParams) (r ListScoresRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PutScore implements putScore operation.
//
// Stores the MusicXML document under the given id, replacing whatever was stored under it before, and
// extracts the metadata the scores are listed by. A document that is not MusicXML, or that carries
// something the server cannot store such as an unknown instrument, is rejected whole: nothing of it is
// left behind.
//
// Requires the `score_editor` role.
//
// PUT /scores/{scoreId}
func (UnimplementedHandler) PutScore(ctx context.Context, req PutScoreReq, params PutScoreParams) (r PutScoreRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *XxxUnknownErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *XxxUnknownErrorStatusCode) {
	r = new(XxxUnknownErrorStatusCode)
	return r
}
