// Code generated by ogen, DO NOT EDIT.

package api

import (
	"bytes"
	"net/http"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
	ht "github.com/ogen-go/ogen/http"
)

func encodePutScoreRequest(
	req PutScoreReq,
	r *http.Request,
) error {
	switch req := req.(type) {
	case *PutScoreReqApplicationVndRecordareMusicxml:
		const contentType = "application/vnd.recordare.musicxml"
		body := req
		ht.SetBody(r, body, contentType)
		return nil
	case *PutScoreReqApplicationVndRecordareMusicxmlXML:
		const contentType = "application/vnd.recordare.musicxml+xml"
		body := req
		ht.SetBody(r, body, contentType)
		return nil
	default:
		return errors.Errorf("unexpected request type: %T", req)
	}
}

func encodePutSetRequest(
	req *WriteSet,
	r *http.Request,
) error {
	const contentType = "application/json"
	e := new(jx.Encoder)
	{
		req.Encode(e)
	}
	encoded := e.Bytes()
	ht.SetBody(r, bytes.NewReader(encoded), contentType)
	return nil
}
