// Code generated by ogen, DO NOT EDIT.
package api

type DeleteSetRes interface {
	deleteSetRes()
}

type GetScoreRes interface {
	getScoreRes()
}

type GetSetRes interface {
	getSetRes()
}

type HealthzRes interface {
	healthzRes()
}

type ListScoresRes interface {
	listScoresRes()
}

type ListSetsRes interface {
	listSetsRes()
}

type PutScoreReq interface {
	putScoreReq()
}

type PutScoreRes interface {
	putScoreRes()
}

type PutSetRes interface {
	putSetRes()
}
