// Code generated by ogen, DO NOT EDIT.

package api

import (
	"fmt"
	"io"
	"time"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
	"github.com/google/uuid"
)

func (s *XxxUnknownErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

type ChangeWindowMoment string

type GetScoreBadRequest ProblemDetails

func (*GetScoreBadRequest) getScoreRes() {}

type GetScoreForbidden ProblemDetails

func (*GetScoreForbidden) getScoreRes() {}

type GetScoreNotFound ProblemDetails

func (*GetScoreNotFound) getScoreRes() {}

// A MusicXML document.
// Ref: #
type GetScoreOKApplicationVndRecordareMusicxml struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetScoreOKApplicationVndRecordareMusicxml) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetScoreOKApplicationVndRecordareMusicxml) getScoreRes() {}

// A MusicXML document.
// Ref: #
type GetScoreOKApplicationVndRecordareMusicxmlXML struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetScoreOKApplicationVndRecordareMusicxmlXML) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetScoreOKApplicationVndRecordareMusicxmlXML) getScoreRes() {}

type GetScoreUnauthorized ProblemDetails

func (*GetScoreUnauthorized) getScoreRes() {}

type GetScoresResponse []Score

func (*GetScoresResponse) listScoresRes() {}

type HealthzOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s HealthzOK) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*HealthzOK) healthzRes() {}

type ListScoresBadRequest ProblemDetails

func (*ListScoresBadRequest) listScoresRes() {}

type ListScoresForbidden ProblemDetails

func (*ListScoresForbidden) listScoresRes() {}

type ListScoresUnauthorized ProblemDetails

func (*ListScoresUnauthorized) listScoresRes() {}

type OAuth2 struct {
	Token  string
	Scopes []string
}

// GetToken returns the value of Token.
func (s *OAuth2) GetToken() string {
	return s.Token
}

// GetScopes returns the value of Scopes.
func (s *OAuth2) GetScopes() []string {
	return s.Scopes
}

// SetToken sets the value of Token.
func (s *OAuth2) SetToken(val string) {
	s.Token = val
}

// SetScopes sets the value of Scopes.
func (s *OAuth2) SetScopes(val []string) {
	s.Scopes = val
}

// What went wrong, in the shape [RFC 9457] gives a failure.
//
// [RFC 9457]: https://www.rfc-editor.org/rfc/rfc9457
// Ref: #
type ProblemDetails struct {
	// What kind of failure this is, as a URI reference. `about:blank` when the failure is no more than its
	// status code, which is all this server tells apart so far.
	Type string `json:"type"`
	// What the kind of failure is called. The same for every failure of a kind, so that it can be shown to
	// a human without reading the detail. With a `type` of `about:blank`, RFC 9457 asks for the status
	// code's own name.
	Title string `json:"title"`
	// The http status code of the answer, repeated here so that the body stands on its own once it has
	// been passed on by something that dropped the rest of the response.
	Status int `json:"status"`
	// What went wrong with this request in particular, meant for a human. It says nothing the caller is
	// not allowed to know: what went wrong inside the server belongs in its log, not in the answer.
	Detail string `json:"detail"`
	// Which occurrence of the problem this was, as a URI reference: the correlation id of the request that
	// failed, written as a URN. It is what the server logged the failure under, so quoting it back is
	// enough to find out what happened inside.
	Instance string `json:"instance"`
	// A code on which an application can act. This is a machine readable code, not meant to display to an
	// end-user, but can be used to show a translated error message.
	//
	// It is what a caller should branch on. `status` says how the request failed in the terms http has,
	// and `detail` says it in the terms a developer reading a log has; neither is stable enough to switch
	// on. This is: the set below only ever grows, and a code is never given a new meaning.
	ErrorCode       ProblemDetailsErrorCode `json:"errorCode"`
	AdditionalProps ProblemDetailsAdditional
}

// GetType returns the value of Type.
func (s *ProblemDetails) GetType() string {
	return s.Type
}

// GetTitle returns the value of Title.
func (s *ProblemDetails) GetTitle() string {
	return s.Title
}

// GetStatus returns the value of Status.
func (s *ProblemDetails) GetStatus() int {
	return s.Status
}

// GetDetail returns the value of Detail.
func (s *ProblemDetails) GetDetail() string {
	return s.Detail
}

// GetInstance returns the value of Instance.
func (s *ProblemDetails) GetInstance() string {
	return s.Instance
}

// GetErrorCode returns the value of ErrorCode.
func (s *ProblemDetails) GetErrorCode() ProblemDetailsErrorCode {
	return s.ErrorCode
}

// GetAdditionalProps returns the value of AdditionalProps.
func (s *ProblemDetails) GetAdditionalProps() ProblemDetailsAdditional {
	return s.AdditionalProps
}

// SetType sets the value of Type.
func (s *ProblemDetails) SetType(val string) {
	s.Type = val
}

// SetTitle sets the value of Title.
func (s *ProblemDetails) SetTitle(val string) {
	s.Title = val
}

// SetStatus sets the value of Status.
func (s *ProblemDetails) SetStatus(val int) {
	s.Status = val
}

// SetDetail sets the value of Detail.
func (s *ProblemDetails) SetDetail(val string) {
	s.Detail = val
}

// SetInstance sets the value of Instance.
func (s *ProblemDetails) SetInstance(val string) {
	s.Instance = val
}

// SetErrorCode sets the value of ErrorCode.
func (s *ProblemDetails) SetErrorCode(val ProblemDetailsErrorCode) {
	s.ErrorCode = val
}

// SetAdditionalProps sets the value of AdditionalProps.
func (s *ProblemDetails) SetAdditionalProps(val ProblemDetailsAdditional) {
	s.AdditionalProps = val
}

type ProblemDetailsAdditional map[string]jx.Raw

func (s *ProblemDetailsAdditional) init() ProblemDetailsAdditional {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// A code on which an application can act. This is a machine readable code, not meant to display to an
// end-user, but can be used to show a translated error message.
//
// It is what a caller should branch on. `status` says how the request failed in the terms http has,
// and `detail` says it in the terms a developer reading a log has; neither is stable enough to switch
// on. This is: the set below only ever grows, and a code is never given a new meaning.
type ProblemDetailsErrorCode string

const (
	ProblemDetailsErrorCodeInvalidRequest       ProblemDetailsErrorCode = "invalid_request"
	ProblemDetailsErrorCodeInvalidMusicXML      ProblemDetailsErrorCode = "invalid_music_xml"
	ProblemDetailsErrorCodeInvalidCredentials   ProblemDetailsErrorCode = "invalid_credentials"
	ProblemDetailsErrorCodeMissingRole          ProblemDetailsErrorCode = "missing_role"
	ProblemDetailsErrorCodeScoreNotFound        ProblemDetailsErrorCode = "score_not_found"
	ProblemDetailsErrorCodeEndpointNotFound     ProblemDetailsErrorCode = "endpoint_not_found"
	ProblemDetailsErrorCodeMethodNotAllowed     ProblemDetailsErrorCode = "method_not_allowed"
	ProblemDetailsErrorCodeUnsupportedMediaType ProblemDetailsErrorCode = "unsupported_media_type"
	ProblemDetailsErrorCodeInternalError        ProblemDetailsErrorCode = "internal_error"
)

// AllValues returns all ProblemDetailsErrorCode values.
func (ProblemDetailsErrorCode) AllValues() []ProblemDetailsErrorCode {
	return []ProblemDetailsErrorCode{
		ProblemDetailsErrorCodeInvalidRequest,
		ProblemDetailsErrorCodeInvalidMusicXML,
		ProblemDetailsErrorCodeInvalidCredentials,
		ProblemDetailsErrorCodeMissingRole,
		ProblemDetailsErrorCodeScoreNotFound,
		ProblemDetailsErrorCodeEndpointNotFound,
		ProblemDetailsErrorCodeMethodNotAllowed,
		ProblemDetailsErrorCodeUnsupportedMediaType,
		ProblemDetailsErrorCodeInternalError,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ProblemDetailsErrorCode) MarshalText() ([]byte, error) {
	switch s {
	case ProblemDetailsErrorCodeInvalidRequest:
		return []byte(s), nil
	case ProblemDetailsErrorCodeInvalidMusicXML:
		return []byte(s), nil
	case ProblemDetailsErrorCodeInvalidCredentials:
		return []byte(s), nil
	case ProblemDetailsErrorCodeMissingRole:
		return []byte(s), nil
	case ProblemDetailsErrorCodeScoreNotFound:
		return []byte(s), nil
	case ProblemDetailsErrorCodeEndpointNotFound:
		return []byte(s), nil
	case ProblemDetailsErrorCodeMethodNotAllowed:
		return []byte(s), nil
	case ProblemDetailsErrorCodeUnsupportedMediaType:
		return []byte(s), nil
	case ProblemDetailsErrorCodeInternalError:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ProblemDetailsErrorCode) UnmarshalText(data []byte) error {
	switch ProblemDetailsErrorCode(data) {
	case ProblemDetailsErrorCodeInvalidRequest:
		*s = ProblemDetailsErrorCodeInvalidRequest
		return nil
	case ProblemDetailsErrorCodeInvalidMusicXML:
		*s = ProblemDetailsErrorCodeInvalidMusicXML
		return nil
	case ProblemDetailsErrorCodeInvalidCredentials:
		*s = ProblemDetailsErrorCodeInvalidCredentials
		return nil
	case ProblemDetailsErrorCodeMissingRole:
		*s = ProblemDetailsErrorCodeMissingRole
		return nil
	case ProblemDetailsErrorCodeScoreNotFound:
		*s = ProblemDetailsErrorCodeScoreNotFound
		return nil
	case ProblemDetailsErrorCodeEndpointNotFound:
		*s = ProblemDetailsErrorCodeEndpointNotFound
		return nil
	case ProblemDetailsErrorCodeMethodNotAllowed:
		*s = ProblemDetailsErrorCodeMethodNotAllowed
		return nil
	case ProblemDetailsErrorCodeUnsupportedMediaType:
		*s = ProblemDetailsErrorCodeUnsupportedMediaType
		return nil
	case ProblemDetailsErrorCodeInternalError:
		*s = ProblemDetailsErrorCodeInternalError
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// ProblemDetailsStatusCode wraps ProblemDetails with StatusCode.
type ProblemDetailsStatusCode struct {
	StatusCode int
	Response   ProblemDetails
}

// GetStatusCode returns the value of StatusCode.
func (s *ProblemDetailsStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ProblemDetailsStatusCode) GetResponse() ProblemDetails {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ProblemDetailsStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ProblemDetailsStatusCode) SetResponse(val ProblemDetails) {
	s.Response = val
}

func (*ProblemDetailsStatusCode) healthzRes() {}

type PutScoreBadRequest ProblemDetails

func (*PutScoreBadRequest) putScoreRes() {}

type PutScoreForbidden ProblemDetails

func (*PutScoreForbidden) putScoreRes() {}

// PutScoreOK is response for PutScore operation.
type PutScoreOK struct{}

func (*PutScoreOK) putScoreRes() {}

// A MusicXML document.
// Ref: #
type PutScoreReqApplicationVndRecordareMusicxml struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s PutScoreReqApplicationVndRecordareMusicxml) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*PutScoreReqApplicationVndRecordareMusicxml) putScoreReq() {}

// A MusicXML document.
// Ref: #
type PutScoreReqApplicationVndRecordareMusicxmlXML struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s PutScoreReqApplicationVndRecordareMusicxmlXML) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*PutScoreReqApplicationVndRecordareMusicxmlXML) putScoreReq() {}

type PutScoreUnauthorized ProblemDetails

func (*PutScoreUnauthorized) putScoreRes() {}

type PutScoreUnsupportedMediaType ProblemDetails

func (*PutScoreUnsupportedMediaType) putScoreRes() {}

// The metadata of a score, extracted from its MusicXML document.
// Ref: #
type Score struct {
	// The id the score was stored under.
	ID uuid.UUID `json:"id"`
	// The work the score is part of. Empty strings when the document names none.
	Work ScoreWork `json:"work"`
	// The movement within the work. Empty strings when the document names none.
	Movement ScoreMovement `json:"movement"`
	// Who wrote the score.
	Creators ScoreCreators `json:"creators"`
	// The languages of the lyrics.
	Languages []string `json:"languages"`
	// The instruments the score is written for.
	Instruments []string `json:"instruments"`
	// When the score was last uploaded.
	LastChangedAt time.Time `json:"last_changed_at"`
	// The tags the score is filed under.
	Tags []string `json:"tags"`
}

// GetID returns the value of ID.
func (s *Score) GetID() uuid.UUID {
	return s.ID
}

// GetWork returns the value of Work.
func (s *Score) GetWork() ScoreWork {
	return s.Work
}

// GetMovement returns the value of Movement.
func (s *Score) GetMovement() ScoreMovement {
	return s.Movement
}

// GetCreators returns the value of Creators.
func (s *Score) GetCreators() ScoreCreators {
	return s.Creators
}

// GetLanguages returns the value of Languages.
func (s *Score) GetLanguages() []string {
	return s.Languages
}

// GetInstruments returns the value of Instruments.
func (s *Score) GetInstruments() []string {
	return s.Instruments
}

// GetLastChangedAt returns the value of LastChangedAt.
func (s *Score) GetLastChangedAt() time.Time {
	return s.LastChangedAt
}

// GetTags returns the value of Tags.
func (s *Score) GetTags() []string {
	return s.Tags
}

// SetID sets the value of ID.
func (s *Score) SetID(val uuid.UUID) {
	s.ID = val
}

// SetWork sets the value of Work.
func (s *Score) SetWork(val ScoreWork) {
	s.Work = val
}

// SetMovement sets the value of Movement.
func (s *Score) SetMovement(val ScoreMovement) {
	s.Movement = val
}

// SetCreators sets the value of Creators.
func (s *Score) SetCreators(val ScoreCreators) {
	s.Creators = val
}

// SetLanguages sets the value of Languages.
func (s *Score) SetLanguages(val []string) {
	s.Languages = val
}

// SetInstruments sets the value of Instruments.
func (s *Score) SetInstruments(val []string) {
	s.Instruments = val
}

// SetLastChangedAt sets the value of LastChangedAt.
func (s *Score) SetLastChangedAt(val time.Time) {
	s.LastChangedAt = val
}

// SetTags sets the value of Tags.
func (s *Score) SetTags(val []string) {
	s.Tags = val
}

func (*Score) getScoreRes() {}

// Who wrote the score.
type ScoreCreators struct {
	Composers []string `json:"composers"`
	Lyricists []string `json:"lyricists"`
}

// GetComposers returns the value of Composers.
func (s *ScoreCreators) GetComposers() []string {
	return s.Composers
}

// GetLyricists returns the value of Lyricists.
func (s *ScoreCreators) GetLyricists() []string {
	return s.Lyricists
}

// SetComposers sets the value of Composers.
func (s *ScoreCreators) SetComposers(val []string) {
	s.Composers = val
}

// SetLyricists sets the value of Lyricists.
func (s *ScoreCreators) SetLyricists(val []string) {
	s.Lyricists = val
}

// The movement within the work. Empty strings when the document names none.
type ScoreMovement struct {
	Title  string `json:"title"`
	Number string `json:"number"`
}

// GetTitle returns the value of Title.
func (s *ScoreMovement) GetTitle() string {
	return s.Title
}

// GetNumber returns the value of Number.
func (s *ScoreMovement) GetNumber() string {
	return s.Number
}

// SetTitle sets the value of Title.
func (s *ScoreMovement) SetTitle(val string) {
	s.Title = val
}

// SetNumber sets the value of Number.
func (s *ScoreMovement) SetNumber(val string) {
	s.Number = val
}

// The work the score is part of. Empty strings when the document names none.
type ScoreWork struct {
	Title  string `json:"title"`
	Number string `json:"number"`
}

// GetTitle returns the value of Title.
func (s *ScoreWork) GetTitle() string {
	return s.Title
}

// GetNumber returns the value of Number.
func (s *ScoreWork) GetNumber() string {
	return s.Number
}

// SetTitle sets the value of Title.
func (s *ScoreWork) SetTitle(val string) {
	s.Title = val
}

// SetNumber sets the value of Number.
func (s *ScoreWork) SetNumber(val string) {
	s.Number = val
}

// XxxUnknownErrorStatusCode wraps ProblemDetails with StatusCode.
type XxxUnknownErrorStatusCode struct {
	StatusCode int
	Response   ProblemDetails
}

// GetStatusCode returns the value of StatusCode.
func (s *XxxUnknownErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *XxxUnknownErrorStatusCode) GetResponse() ProblemDetails {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *XxxUnknownErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *XxxUnknownErrorStatusCode) SetResponse(val ProblemDetails) {
	s.Response = val
}
