// Code generated by ogen, DO NOT EDIT.
package api

type GetScoreRes interface {
	getScoreRes()
}

type HealthzRes interface {
	healthzRes()
}

type ListScoresRes interface {
	listScoresRes()
}

type PutScoreReq interface {
	putScoreReq()
}

type PutScoreRes interface {
	putScoreRes()
}
