// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	GetScoreOperation   OperationName = "GetScore"
	HealthzOperation    OperationName = "Healthz"
	ListScoresOperation OperationName = "ListScores"
	PutScoreOperation   OperationName = "PutScore"
)
