// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// GetScoreParams is parameters of getScore operation.
type GetScoreParams struct {
	// The id the score is stored under.
	ScoreId uuid.UUID
}

func unpackGetScoreParams(packed middleware.Parameters) (params GetScoreParams) {
	{
		key := middleware.ParameterKey{
			Name: "scoreId",
			In:   "path",
		}
		params.ScoreId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetScoreParams(args [1]string, argsEscaped bool, r *http.Request) (params GetScoreParams, _ error) {
	// Decode path: scoreId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "scoreId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.ScoreId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "scoreId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// ListScoresParams is parameters of listScores operation.
type ListScoresParams struct {
	// The start of the change window, inclusive.
	ChangesSince ChangeWindowMoment
	// The end of the change window, inclusive.
	ChangesUntil ChangeWindowMoment
}

func unpackListScoresParams(packed middleware.Parameters) (params ListScoresParams) {
	{
		key := middleware.ParameterKey{
			Name: "Changes-Since",
			In:   "query",
		}
		params.ChangesSince = packed[key].(ChangeWindowMoment)
	}
	{
		key := middleware.ParameterKey{
			Name: "Changes-Until",
			In:   "query",
		}
		params.ChangesUntil = packed[key].(ChangeWindowMoment)
	}
	return params
}

func decodeListScoresParams(args [0]string, argsEscaped bool, r *http.Request) (params ListScoresParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: Changes-Since.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "Changes-Since",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotChangesSinceVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotChangesSinceVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.ChangesSince = ChangeWindowMoment(paramsDotChangesSinceVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if err := params.ChangesSince.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "Changes-Since",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: Changes-Until.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "Changes-Until",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotChangesUntilVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotChangesUntilVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.ChangesUntil = ChangeWindowMoment(paramsDotChangesUntilVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if err := params.ChangesUntil.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "Changes-Until",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// PutScoreParams is parameters of putScore operation.
type PutScoreParams struct {
	// The id the score is stored under.
	ScoreId uuid.UUID
}

func unpackPutScoreParams(packed middleware.Parameters) (params PutScoreParams) {
	{
		key := middleware.ParameterKey{
			Name: "scoreId",
			In:   "path",
		}
		params.ScoreId = packed[key].(uuid.UUID)
	}
	return params
}

func decodePutScoreParams(args [1]string, argsEscaped bool, r *http.Request) (params PutScoreParams, _ error) {
	// Decode path: scoreId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "scoreId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.ScoreId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "scoreId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
