// Code generated by ogen, DO NOT EDIT.

package api

// setDefaults set default value of fields.
func (s *EntryView) setDefaults() {
	{
		val := float64(1)
		s.Zoom = val
	}
}

// setDefaults set default value of fields.
func (s *WriteEntryView) setDefaults() {
	{
		val := float64(1)
		s.Zoom.SetTo(val)
	}
}
