name: core
description: The domain independant logic
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  freezed_annotation:
  hive:
  logger:

dev_dependencies:
  async:
  build_runner:
  firebase_performance:
  freezed:
  lint:
  testing:
    path: ../testing

