name: score
description: The score app
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  auto_route: ">=6.0.0 <7.0.0"
  cloud_firestore: ">=4.4.5 <5.0.0"
  firebase_core: ">=2.8.0 <3.0.0"
  flutter:
    sdk: flutter
  flutter_fox_logging: ">=1.0.0 <2.0.0"
  flutter_localizations:
    sdk: flutter
  flutterfire_ui: ">0.0.0 <1.0.0"
  get_it: ">=7.0.0 <8.0.0"
  google_fonts: ">=4.0.3 <5.0.0"
  logging:

dev_dependencies:
  auto_route_generator: ">=6.0.0 <7.0.0"
  build_runner: ">=2.0.0 <3.0.0"
  flutter_test:
    sdk: flutter
  lint:

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/scoresx.json