name: score
description: The score app
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  algolia: ">=1.0.0 <2.0.0"
  auto_route: ">=4.0.0 <5.0.0"
  behaviour: ">0.0.0 <1.0.0"
  cloud_firestore: ">=3.0.0 <4.0.0"
  equatable: ">=2.0.0 <3.0.0"
  firebase_analytics: ">=9.0.0 <10.0.0"
  firebase_auth: ">=3.0.0 <4.0.0"
  firebase_core: ">=1.0.0 <2.0.0"
  firebase_remote_config: ">=2.0.0 <3.0.0"
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_logging_extensions:
    git:
      url: https://github.com/wim07101993/flutter_logging_extensions.git
  flutter_secure_storage: ">=5.0.0 <6.0.0"
  flutterfire_ui: ">0.0.0 <1.0.0"
  font_awesome_flutter: ">=10.0.0 <11.0.0"
  freezed_annotation: ">=2.0.0 <3.0.0"
  get_it: ">=7.0.0 <8.0.0"
  google_fonts: ">=3.0.0 <4.0.0"
  hawk:
    git:
      url: https://github.com/wim07101993/hawk.git
  hive: ">=2.0.0 <3.0.0"
  hive_flutter: ">=1.0.0 <2.0.0"
  infinite_scroll_pagination: ">=3.0.0 <4.0.0"
  intl: ">0.0.0 <1.0.0"
  json_annotation: ">=4.6.0 <5.0.0"
  package_info_plus: ">=1.0.0 <2.0.0"
  path_provider: ">=2.0.0 <3.0.0"
  provider: ">=6.0.0 <7.0.0"
  uuid: ">=3.0.0 <4.0.0"

dev_dependencies:
  auto_route_generator: ">=4.0.0 <5.0.0"
  build_runner: ">=2.0.0 <3.0.0"
  flutter_test:
    sdk: flutter
  freezed: ">=2.0.0 <3.0.0"
  hive_generator: ">=1.0.0 <2.0.0"
  json_serializable: ">=6.0.0 <7.0.0"
  lint:

flutter:
  generate: true
  uses-material-design: true