name: score
description: The score app
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  auto_route: ^3.2.4
  behaviour: ^0.0.1
  bloc: ^8.0.3
  cloud_firestore: ^3.1.13
  equatable: ^2.0.3
  firebase_auth: ^3.3.15
  firebase_core: ^1.15.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_logging_extensions:
    git:
      url: https://github.com/wim07101993/flutter_logging_extensions.git
  flutter_secure_storage: ^5.0.2
  flutterfire_ui: ^0.4.0+3
  font_awesome_flutter: ^10.1.0
  freezed_annotation: ^2.0.1
  get_it: ^7.2.0
  google_fonts: ^2.3.1
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  package_info_plus: ^1.4.2
  path_provider: ^2.0.9
  provider: ^6.0.2
  uuid: ^3.0.6

dev_dependencies:
  auto_route_generator:
  build_runner:
  flutter_test:
    sdk: flutter
  freezed:
  hive_generator:
  lint:

flutter:
  generate: true
  uses-material-design: true