name: score
description: The score app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  auto_route: ^3.2.1
  firebase_auth: ^3.3.5
  firebase_auth_desktop: ^0.1.1-dev.3
  firebase_core: ^1.11.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_logging_extensions:
    git:
      url: https://github.com/wim07101993/flutter_logging_extensions.git
  flutter_secure_storage: ^5.0.2
  flutterfire_ui: ^0.3.1
  get_it: ^7.2.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  package_info_plus: ^1.3.0
  path_provider: ^2.0.8
  provider: ^6.0.2
  uuid: ^3.0.5

dev_dependencies:
  auto_route_generator:
  build_runner:
  flutter_test:
    sdk: flutter
  hive_generator:
  lint:

flutter:
  generate: true
  uses-material-design: true