name: score
description: An application to manage and view my scores.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  async:
  auto_route:
  bloc:
  cloud_firestore:
  core:
    path: ../core
  firebase_auth:
  firebase_core:
  flutter:
    sdk: flutter
  flutter_bloc:
  flutter_signin_button:
  get_it:
  google_sign_in:
  hive:
  provider:

dev_dependencies:
  auto_route_generator:
  build_runner:
  flutter_test:
    sdk: flutter
  freezed:
  hive_generator:
  json_serializable:
  lint:

flutter:
  uses-material-design: true
