name: score
description: An application to manage and view my scores.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^7.0.0
  core:
    path: ../core
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.1
  get_it: ^7.2.0
  google_sign_in: ^5.0.5
  hive: ^2.0.4
  provider: ^5.0.0

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  freezed:
  hive_generator:
  lint:

flutter:
  uses-material-design: true
