name: app
description: The score app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  auto_route: ^3.2.1
  firebase_auth: ^3.3.4
  firebase_auth_desktop: ^0.1.1-dev.3
  firebase_core: ^1.10.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  get_it: ^7.2.0
  intl: ^0.17.0
  provider: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint:

flutter:
  generate: true
  uses-material-design: true