### Index all file which have changed in the first month
GRPC {{host}}/score.Indexer/IndexScores
Content-Type: application/json
Authorization: bearer {{$auth.token("local")}}

{
  "since": "2024-03-01T00:00:00Z",
  "until": "2024-04-01T00:00:00Z"
}

