### Retrieves a single score from the api
GRPC {{host}}/score.Searcher/GetScore
Authorization: bearer {{$auth.token("local")}}

{
  "score_id": "0e415222-cd34-44d7-a6ff-3369a568583a"
}

### Retrieves all scores from the api
GRPC {{host}}/score.Searcher/GetAllScores
Authorization: bearer {{$auth.token("local")}}

{
  "page_size": 100
}

