name: score_shared
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/wim07101993/score

environment:
  sdk: ^3.2.3

dependencies:

dev_dependencies:
  lint: ^2.0.0
  test: ^1.24.0
