// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:score/features/logging/logging_behaviour_track.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BehaviourLogObjectAdapter());
  }
}
