name: Build Docker image

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [ "master" ]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: docker build . --file backend.Dockerfile

  build-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build . --file frontend/frontend.Dockerfile
