name: Release-Dev

on:
  workflow_dispatch:
  push:
    branches: 
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build and Push backend image
        uses: docker/build-push-action@v6
        with:
          file: backend.Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/score:dev-latest

      - name: Set config
        run: cp frontend/src/config.dev.js frontend/src/config.js
        
      - name: Build and Push frondend
        uses: docker/build-push-action@v6
        with:
          file: frontend/frontend.Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/score-frontend:dev-latest       
