name: Release

on:
  workflow_dispatch:
  push:
    tags: 
    - 'v*'

jobs:
  build:
    name: Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build and Push backend image
        uses: docker/build-push-action@v6
        with:
          file: backend.Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/score:${{ github.ref_name }} , ${{ secrets.DOCKER_USERNAME }}/score:latest

      - name: Build and Push frondend
        uses: docker/build-push-action@v6
        with:
          file: frontend/frontend.Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/score:${{ github.ref_name }} , ${{ secrets.DOCKER_USERNAME }}/score-frontend:latest
      

      - name: Create release
        uses: ncipollo/release-action@v1
